services:
  - type: web
    name: medical-assistant
    env: node
    plan: free
    buildCommand: python3 -m pip install -r ml/requirements.txt && npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_EXECUTABLE
        value: python3
